name: paisa
description: A expense manager app for Android, iOS, Web & Windows.

publish_to: "none"

version: 5.2.0+520

environment:
  sdk: ">=3.0.2 <4.0.0"
  flutter: ^3.17.0

dependencies:
  animations: ^2.0.7
  bezier_chart_plus: ^0.0.1
  chart_sparkline: ^1.0.13
  collection: ^1.17.0
  csv: ^5.0.1
  dartz: ^0.10.1
  date_picker_timeline: ^1.2.3
  device_info_plus:
  dynamic_color: ^1.6.5
  equatable: ^2.0.5
  file_picker: ^5.2.5
  fl_chart: ^0.63.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_displaymode: ^0.6.0
  flutter_localizations:
    sdk: flutter
  flutter_slidable: ^3.0.0
  get_it: ^7.2.0
  glassmorphism: ^3.0.0
  go_router: ^10.1.2
  google_fonts: ^6.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.0.0
  in_app_review: ^2.0.6
  in_app_update: ^4.1.4
  injectable: ^2.1.0
  intl: ^0.18.0
  local_auth: ^2.1.3
  material_color_utilities: ^0.8.0
  material_design_icons_flutter: ^7.0.7296
  package_info_plus: ^4.0.2
  path_provider: ^2.0.11
  permission_handler: ^11.0.0
  provider: ^6.0.5
  quick_actions: ^1.0.2
  responsive_builder: ^0.7.0
  share_plus: ^7.0.2
  url_launcher: ^6.1.7
  url_strategy: ^0.2.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  event_bus_plus: ^0.6.1
  flutter_colorpicker: ^1.0.3
  rust_builder:
    path: rust_builder
  flutter_rust_bridge: 2.0.0-dev.22

dev_dependencies:
  build_runner: ^2.3.2
  change_app_package_name: any
  flutter_app_name: ^0.1.1
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.2.0+1
  hive_generator: ^2.0.0
  injectable_generator: ^2.1.4
  msix: ^3.7.0
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  integration_test:
    sdk: flutter

dependency_overrides:
  #intl: ^0.18.0
  #material_color_utilities: ^0.2.0

flutter_app_name:
  name: "Quotient"

flutter_launcher_icons:
  image_path: "assets/images/icon.png"
  macos:
    generate: true
    image_path: "assets/images/icon.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/icon.png
  color_dark: "#121212"
  android: true
  ios: true
  android_12:
    image: assets/images/icon_light.png
    icon_background_color: "#ffffff"
    image_dark: assets/images/icon_dark.png
    icon_background_color_dark: "#121212"

flutter_icons:
  ios: true
  android: false
  image_path: "assets/images/icon.png"
  image_path_ios: "assets/images/ios_app_icon.png"
  remove_alpha_ios: true

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/icon.png
